apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-name-backend
spec:
  selector:
    matchLabels:
      app: your-app-name-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: your-app-name-backend
    spec:
      containers:
        - name: your-app-name-backend
          image: your-docker-registry/your-openshift-project/your-app-name-backend
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-name-backend
spec:
  selector:
    app: your-app-name-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
